### PR TITLE
[change]  Set tab size to 2

### PR DESCRIPTION
**Pull request by ongaeshi**

### CODE REVIEW

**Comment by nwtgck** [comment]
Thanks to your PR!

## Shorter is Better

The PR makes <kbd>tab</kbd> be two spaces in Ruby mode. I prefer 2 spaces than tabs to indent. So, in my project, except Go language, I use 2 spaces to indent. However, I think that **shorter is better in URL of Nipp.**  That is a reason why I use tab to indent in Nipp.

## Proposal

But, tab takes too much space to indent. So, nest seems to be deep, and it's not easy to read. I think change of only apperence of tab is better.

**Comment by nwtgck** [comment]
@ongaeshi 

I'd like to merge this. Could you use 2 spaces for "ES2017" and "ES2017 Function" for consistency not only Ruby mode?

**Comment by ongaeshi** [comment]
@nwtgck 

Your short URL concept is very interesting.
I had not thought so deeply.

I have changed to use 2 spaces for "ES2017" and "ES2017 Function". (cd4f37c78aeef6af6ea2b01695397870ce2b3ebc)

Thank you.

**Comment by nwtgck** [comment]
@ongaeshi Thanks! I'll merge this.

**Pull request merged**
